sudo: required

language: c

services:
  - docker

git:
  submodules: false

before_install:
  - git submodule update --init --recursive --depth=1

script:
  - docker run -v $PWD:/app -w /app componolit/ci:gnat-community-2020 /bin/sh -c "make"
